kind: Deployment
apiVersion: apps/v1
metadata:
  name: keepalive
  namespace: keepalive
  labels:
    app: keepalive
    app.kubernetes.io/component: keepalive
    app.kubernetes.io/instance: keepalive
    app.kubernetes.io/part-of: keepalive-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keepalive
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: keepalive
        deploymentconfig: keepalive
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      volumes:
        - name: keepalive-vol
          configMap:
            name: keepalive-conf
            defaultMode: 420
      containers:
        - name: keepalive
          image: {{ .Values.containers.repository }}/{{ .Values.containers.image }}:{{ .Values.containers.version }} 
          ports: 
            - containerPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: keepalive-vol
              mountPath: /home/app_python/conf
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
